import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import NextTopLoader from 'nextjs-toploader';
import AuthProvider from "@/context/AuthProvider";
import TokenRefresher from "@/components/TokenRefresher";
import Footer from "@/components/Footer";

const roboto = Roboto({
   weight: ["400"],
   subsets: ["latin"]
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${roboto.className} bg-background text-text`}>
            <NextTopLoader
               height={5}
               showSpinner={false}
            />
            <Toaster
               position="top-right"
               reverseOrder={false}
            />
            <AuthProvider>
               <TokenRefresher />
               <div className=" max-w-screen-xl mx-auto">
                  <Navbar />
                  <main className="px-3 min-h-screen">
                     {children}
                  </main>
                  <Footer />
               </div>
            </AuthProvider>
         </body>
      </html>
   );
}
